//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StabilityMatrix.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StabilityMatrix.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModels inheriting from ViewModelBase rely on lifecycle methods (OnLoaded/OnUnloaded) called by UserControlBase or TemplatedControlBase. Ensure the control specified in the [View] attribute inherits from one of these..
        /// </summary>
        internal static string SM0001_Description {
            get {
                return ResourceManager.GetString("SM0001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control &apos;{0}&apos; must inherit from &apos;{2}&apos; or &apos;{3}&apos; because its associated ViewModel &apos;{1}&apos; inherits from ViewModelBase.
        /// </summary>
        internal static string SM0001_MessageFormat {
            get {
                return ResourceManager.GetString("SM0001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control associated with ViewModelBase must inherit UserControlBase or TemplatedControlBase.
        /// </summary>
        internal static string SM0001_Title {
            get {
                return ResourceManager.GetString("SM0001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete ViewModels inheriting from ViewModelBase should specify their associated UI control via the [View(typeof(YourControl))] attribute..
        /// </summary>
        internal static string SM0002_Description {
            get {
                return ResourceManager.GetString("SM0002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel &apos;{0}&apos; inherits from ViewModelBase but does not have a [View(...)] attribute to specify its corresponding control.
        /// </summary>
        internal static string SM0002_MessageFormat {
            get {
                return ResourceManager.GetString("SM0002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel inheriting ViewModelBase should have a [View] attribute.
        /// </summary>
        internal static string SM0002_Title {
            get {
                return ResourceManager.GetString("SM0002_Title", resourceCulture);
            }
        }
    }
}
