//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StabilityMatrix.Avalonia.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StabilityMatrix.Avalonia.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add for All Users.
        /// </summary>
        public static string Action_AddForAllUsers {
            get {
                return ResourceManager.GetString("Action_AddForAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add for Current User.
        /// </summary>
        public static string Action_AddForCurrentUser {
            get {
                return ResourceManager.GetString("Action_AddForCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Package.
        /// </summary>
        public static string Action_AddPackage {
            get {
                return ResourceManager.GetString("Action_AddPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string Action_CheckForUpdates {
            get {
                return ResourceManager.GetString("Action_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Version.
        /// </summary>
        public static string Action_CheckVersion {
            get {
                return ResourceManager.GetString("Action_CheckVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Action_Close {
            get {
                return ResourceManager.GetString("Action_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Action_Connect {
            get {
                return ResourceManager.GetString("Action_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Action_Continue {
            get {
                return ResourceManager.GetString("Action_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Action_Edit {
            get {
                return ResourceManager.GetString("Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        public static string Action_ExitApplication {
            get {
                return ResourceManager.GetString("Action_ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Action_Import {
            get {
                return ResourceManager.GetString("Action_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Action_Install {
            get {
                return ResourceManager.GetString("Action_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Action_Launch {
            get {
                return ResourceManager.GetString("Action_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Action_New {
            get {
                return ResourceManager.GetString("Action_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Action_OK {
            get {
                return ResourceManager.GetString("Action_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Browser.
        /// </summary>
        public static string Action_OpenInBrowser {
            get {
                return ResourceManager.GetString("Action_OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Explorer.
        /// </summary>
        public static string Action_OpenInExplorer {
            get {
                return ResourceManager.GetString("Action_OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Finder.
        /// </summary>
        public static string Action_OpenInFinder {
            get {
                return ResourceManager.GetString("Action_OpenInFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on CivitAI.
        /// </summary>
        public static string Action_OpenOnCivitAi {
            get {
                return ResourceManager.GetString("Action_OpenOnCivitAi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Web UI.
        /// </summary>
        public static string Action_OpenWebUI {
            get {
                return ResourceManager.GetString("Action_OpenWebUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Action_Quit {
            get {
                return ResourceManager.GetString("Action_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunch.
        /// </summary>
        public static string Action_Relaunch {
            get {
                return ResourceManager.GetString("Action_Relaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunch Later.
        /// </summary>
        public static string Action_RelaunchLater {
            get {
                return ResourceManager.GetString("Action_RelaunchLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Action_Remove {
            get {
                return ResourceManager.GetString("Action_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Action_Rename {
            get {
                return ResourceManager.GetString("Action_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Action_Restart {
            get {
                return ResourceManager.GetString("Action_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Action_Retry {
            get {
                return ResourceManager.GetString("Action_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Action_Search {
            get {
                return ResourceManager.GetString("Action_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Directory.
        /// </summary>
        public static string Action_SelectDirectory {
            get {
                return ResourceManager.GetString("Action_SelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Action_Send {
            get {
                return ResourceManager.GetString("Action_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Input.
        /// </summary>
        public static string Action_SendInput {
            get {
                return ResourceManager.GetString("Action_SendInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Explorer.
        /// </summary>
        public static string Action_ShowInExplorer {
            get {
                return ResourceManager.GetString("Action_ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Action_Stop {
            get {
                return ResourceManager.GetString("Action_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Action_Uninstall {
            get {
                return ResourceManager.GetString("Action_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Action_Update {
            get {
                return ResourceManager.GetString("Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Action_Yes {
            get {
                return ResourceManager.GetString("Action_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Label_About {
            get {
                return ResourceManager.GetString("Label_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Stability Matrix to the Start Menu.
        /// </summary>
        public static string Label_AddToStartMenu {
            get {
                return ResourceManager.GetString("Label_AddToStartMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses the current app location, you can run this again if you move the app.
        /// </summary>
        public static string Label_AddToStartMenu_Details {
            get {
                return ResourceManager.GetString("Label_AddToStartMenu_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Options.
        /// </summary>
        public static string Label_AdvancedOptions {
            get {
                return ResourceManager.GetString("Label_AdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Versions.
        /// </summary>
        public static string Label_AllVersions {
            get {
                return ResourceManager.GetString("Label_AllVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Label_Appearance {
            get {
                return ResourceManager.GetString("Label_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically scroll to end of console output.
        /// </summary>
        public static string Label_AutoScrollToEnd {
            get {
                return ResourceManager.GetString("Label_AutoScrollToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Model.
        /// </summary>
        public static string Label_BaseModel {
            get {
                return ResourceManager.GetString("Label_BaseModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a Patron.
        /// </summary>
        public static string Label_BecomeAPatron {
            get {
                return ResourceManager.GetString("Label_BecomeAPatron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Label_Branch {
            get {
                return ResourceManager.GetString("Label_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Label_Branches {
            get {
                return ResourceManager.GetString("Label_Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callstack.
        /// </summary>
        public static string Label_Callstack {
            get {
                return ResourceManager.GetString("Label_Callstack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Label_Categories {
            get {
                return ResourceManager.GetString("Label_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFG Scale.
        /// </summary>
        public static string Label_CFGScale {
            get {
                return ResourceManager.GetString("Label_CFGScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpoint Manager.
        /// </summary>
        public static string Label_CheckpointManager {
            get {
                return ResourceManager.GetString("Label_CheckpointManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close dialog when finished.
        /// </summary>
        public static string Label_CloseDialogWhenFinished {
            get {
                return ResourceManager.GetString("Label_CloseDialogWhenFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Label_Comments {
            get {
                return ResourceManager.GetString("Label_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        public static string Label_Commit {
            get {
                return ResourceManager.GetString("Label_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string Label_ConfirmDelete {
            get {
                return ResourceManager.GetString("Label_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm?.
        /// </summary>
        public static string Label_ConfirmQuestion {
            get {
                return ResourceManager.GetString("Label_ConfirmQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected Model.
        /// </summary>
        public static string Label_ConnectedModel {
            get {
                return ResourceManager.GetString("Label_ConnectedModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string Label_ConnectingEllipsis {
            get {
                return ResourceManager.GetString("Label_ConnectingEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current directory:.
        /// </summary>
        public static string Label_CurrentDirectory {
            get {
                return ResourceManager.GetString("Label_CurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Directory.
        /// </summary>
        public static string Label_DataDirectory {
            get {
                return ResourceManager.GetString("Label_DataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where application data (model checkpoints, web UIs, etc.) will be installed..
        /// </summary>
        public static string Label_DataDirectoryExplanation {
            get {
                return ResourceManager.GetString("Label_DataDirectoryExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Folder Name.
        /// </summary>
        public static string Label_DataFolderName {
            get {
                return ResourceManager.GetString("Label_DataFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data provided by CivitAI.
        /// </summary>
        public static string Label_DataProvidedByCivitAi {
            get {
                return ResourceManager.GetString("Label_DataProvidedByCivitAi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deemphasis.
        /// </summary>
        public static string Label_Deemphasis {
            get {
                return ResourceManager.GetString("Label_Deemphasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denoising Strength.
        /// </summary>
        public static string Label_DenoisingStrength {
            get {
                return ResourceManager.GetString("Label_DenoisingStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Label_Details {
            get {
                return ResourceManager.GetString("Label_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Rich Presence.
        /// </summary>
        public static string Label_DiscordRichPresence {
            get {
                return ResourceManager.GetString("Label_DiscordRichPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string Label_DisplayName {
            get {
                return ResourceManager.GetString("Label_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Label_Downloads {
            get {
                return ResourceManager.GetString("Label_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp; Drop checkpoints here to import.
        /// </summary>
        public static string Label_DragAndDropCheckpointsHereToImport {
            get {
                return ResourceManager.GetString("Label_DragAndDropCheckpointsHereToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop file here to import.
        /// </summary>
        public static string Label_DropFileToImport {
            get {
                return ResourceManager.GetString("Label_DropFileToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded Python.
        /// </summary>
        public static string Label_EmbeddedPython {
            get {
                return ResourceManager.GetString("Label_EmbeddedPython", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emebeddings / Textual Inversion.
        /// </summary>
        public static string Label_EmbeddingsOrTextualInversion {
            get {
                return ResourceManager.GetString("Label_EmbeddingsOrTextualInversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emphasis.
        /// </summary>
        public static string Label_Emphasis {
            get {
                return ResourceManager.GetString("Label_Emphasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Variables.
        /// </summary>
        public static string Label_EnvironmentVariables {
            get {
                return ResourceManager.GetString("Label_EnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_EnvVarsTable_Name {
            get {
                return ResourceManager.GetString("Label_EnvVarsTable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Label_EnvVarsTable_Value {
            get {
                return ResourceManager.GetString("Label_EnvVarsTable_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error installing package.
        /// </summary>
        public static string Label_ErrorInstallingPackage {
            get {
                return ResourceManager.GetString("Label_ErrorInstallingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may encounter errors when using a FAT32 or exFAT drive. Select a different drive for a smoother experience..
        /// </summary>
        public static string Label_FatWarning {
            get {
                return ResourceManager.GetString("Label_FatWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Connected Metadata.
        /// </summary>
        public static string Label_FindConnectedMetadata {
            get {
                return ResourceManager.GetString("Label_FindConnectedMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page.
        /// </summary>
        public static string Label_FirstPage {
            get {
                return ResourceManager.GetString("Label_FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Label_Folder {
            get {
                return ResourceManager.GetString("Label_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Label_Height {
            get {
                return ResourceManager.GetString("Label_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import as Connected.
        /// </summary>
        public static string Label_ImportAsConnected {
            get {
                return ResourceManager.GetString("Label_ImportAsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for connected metadata on new local imports.
        /// </summary>
        public static string Label_ImportAsConnectedExplanation {
            get {
                return ResourceManager.GetString("Label_ImportAsConnectedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Latest -.
        /// </summary>
        public static string Label_ImportLatest {
            get {
                return ResourceManager.GetString("Label_ImportLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing....
        /// </summary>
        public static string Label_Indexing {
            get {
                return ResourceManager.GetString("Label_Indexing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner exception.
        /// </summary>
        public static string Label_InnerException {
            get {
                return ResourceManager.GetString("Label_InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Label_Input {
            get {
                return ResourceManager.GetString("Label_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input required.
        /// </summary>
        public static string Label_InputRequired {
            get {
                return ResourceManager.GetString("Label_InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An installation with this name already exists..
        /// </summary>
        public static string Label_InstallationWithThisNameExists {
            get {
                return ResourceManager.GetString("Label_InstallationWithThisNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        public static string Label_Installing {
            get {
                return ResourceManager.GetString("Label_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrations.
        /// </summary>
        public static string Label_Integrations {
            get {
                return ResourceManager.GetString("Label_Integrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Package type.
        /// </summary>
        public static string Label_InvalidPackageType {
            get {
                return ResourceManager.GetString("Label_InvalidPackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Discord Server.
        /// </summary>
        public static string Label_JoinDiscord {
            get {
                return ResourceManager.GetString("Label_JoinDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page.
        /// </summary>
        public static string Label_LastPage {
            get {
                return ResourceManager.GetString("Label_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started.
        /// </summary>
        public static string Label_LetsGetStarted {
            get {
                return ResourceManager.GetString("Label_LetsGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string Label_License {
            get {
                return ResourceManager.GetString("Label_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Agreement..
        /// </summary>
        public static string Label_LicenseAgreement {
            get {
                return ResourceManager.GetString("Label_LicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License and Open Source Notices.
        /// </summary>
        public static string Label_LicenseAndOpenSourceNotices {
            get {
                return ResourceManager.GetString("Label_LicenseAndOpenSourceNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Model.
        /// </summary>
        public static string Label_LocalModel {
            get {
                return ResourceManager.GetString("Label_LocalModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Label_Model {
            get {
                return ResourceManager.GetString("Label_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Description.
        /// </summary>
        public static string Label_ModelDescription {
            get {
                return ResourceManager.GetString("Label_ModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search models, #tags, or @users.
        /// </summary>
        public static string Label_ModelSearchWatermark {
            get {
                return ResourceManager.GetString("Label_ModelSearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models Folder.
        /// </summary>
        public static string Label_ModelsFolder {
            get {
                return ResourceManager.GetString("Label_ModelsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Type.
        /// </summary>
        public static string Label_ModelType {
            get {
                return ResourceManager.GetString("Label_ModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networks (Lora / LyCORIS).
        /// </summary>
        public static string Label_NetworksLoraOrLycoris {
            get {
                return ResourceManager.GetString("Label_NetworksLoraOrLycoris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of Stability Matrix is available!.
        /// </summary>
        public static string Label_NewVersionAvailable {
            get {
                return ResourceManager.GetString("Label_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Image.
        /// </summary>
        public static string Label_NextImage {
            get {
                return ResourceManager.GetString("Label_NextImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string Label_NextPage {
            get {
                return ResourceManager.GetString("Label_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Label_No {
            get {
                return ResourceManager.GetString("Label_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only available on Windows.
        /// </summary>
        public static string Label_OnlyAvailableOnWindows {
            get {
                return ResourceManager.GetString("Label_OnlyAvailableOnWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Environment.
        /// </summary>
        public static string Label_PackageEnvironment {
            get {
                return ResourceManager.GetString("Label_PackageEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Type.
        /// </summary>
        public static string Label_PackageType {
            get {
                return ResourceManager.GetString("Label_PackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Uninstalled.
        /// </summary>
        public static string Label_PackageUninstalled {
            get {
                return ResourceManager.GetString("Label_PackageUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Label_Page {
            get {
                return ResourceManager.GetString("Label_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a different name or select a different install location..
        /// </summary>
        public static string Label_PleaseChooseDifferentName {
            get {
                return ResourceManager.GetString("Label_PleaseChooseDifferentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Data Directory.
        /// </summary>
        public static string Label_PleaseSelectDataDirectory {
            get {
                return ResourceManager.GetString("Label_PleaseSelectDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Mode.
        /// </summary>
        public static string Label_PortableMode {
            get {
                return ResourceManager.GetString("Label_PortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Portable Mode, all data and settings will be stored in the same directory as the application. You will be able to move the application with its &apos;Data&apos; folder to a different location or computer..
        /// </summary>
        public static string Label_PortableModeExplanation {
            get {
                return ResourceManager.GetString("Label_PortableModeExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Image.
        /// </summary>
        public static string Label_PreviousImage {
            get {
                return ResourceManager.GetString("Label_PreviousImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string Label_PreviousPage {
            get {
                return ResourceManager.GetString("Label_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python Version Info.
        /// </summary>
        public static string Label_PythonVersionInfo {
            get {
                return ResourceManager.GetString("Label_PythonVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PyTorch Version.
        /// </summary>
        public static string Label_PyTorchVersion {
            get {
                return ResourceManager.GetString("Label_PyTorchVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agree to the.
        /// </summary>
        public static string Label_ReadAndAgree {
            get {
                return ResourceManager.GetString("Label_ReadAndAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refiner.
        /// </summary>
        public static string Label_Refiner {
            get {
                return ResourceManager.GetString("Label_Refiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunch Required.
        /// </summary>
        public static string Label_RelaunchRequired {
            get {
                return ResourceManager.GetString("Label_RelaunchRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases.
        /// </summary>
        public static string Label_Releases {
            get {
                return ResourceManager.GetString("Label_Releases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove shared checkpoints directory symbolic links on shutdown.
        /// </summary>
        public static string Label_RemoveSymlinksOnShutdown {
            get {
                return ResourceManager.GetString("Label_RemoveSymlinksOnShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option if you&apos;re having problems moving Stability Matrix to another drive.
        /// </summary>
        public static string Label_RemoveSymlinksOnShutdown_Details {
            get {
                return ResourceManager.GetString("Label_RemoveSymlinksOnShutdown_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Checkpoints Cache.
        /// </summary>
        public static string Label_ResetCheckpointsCache {
            get {
                return ResourceManager.GetString("Label_ResetCheckpointsCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuilds the installed checkpoints cache. Use if checkpoints are incorrectly labeled in the Model Browser.
        /// </summary>
        public static string Label_ResetCheckpointsCache_Details {
            get {
                return ResourceManager.GetString("Label_ResetCheckpointsCache_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Label_SearchEllipsis {
            get {
                return ResourceManager.GetString("Label_SearchEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select new Data Directory.
        /// </summary>
        public static string Label_SelectNewDataDirectory {
            get {
                return ResourceManager.GetString("Label_SelectNewDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not move existing data.
        /// </summary>
        public static string Label_SelectNewDataDirectory_Details {
            get {
                return ResourceManager.GetString("Label_SelectNewDataDirectory_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Model Folder Strategy.
        /// </summary>
        public static string Label_SharedModelFolderStrategy {
            get {
                return ResourceManager.GetString("Label_SharedModelFolderStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Sharing.
        /// </summary>
        public static string Label_SharedModelStrategyShort {
            get {
                return ResourceManager.GetString("Label_SharedModelStrategyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Model Images.
        /// </summary>
        public static string Label_ShowModelImages {
            get {
                return ResourceManager.GetString("Label_ShowModelImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show NSFW Content.
        /// </summary>
        public static string Label_ShowNsfwContent {
            get {
                return ResourceManager.GetString("Label_ShowNsfwContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show pixel grid at high zoom levels.
        /// </summary>
        public static string Label_ShowPixelGridAtHighZoomLevels {
            get {
                return ResourceManager.GetString("Label_ShowPixelGridAtHighZoomLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip first-time setup.
        /// </summary>
        public static string Label_SkipSetup {
            get {
                return ResourceManager.GetString("Label_SkipSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Label_Sort {
            get {
                return ResourceManager.GetString("Label_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stability Matrix.
        /// </summary>
        public static string Label_StabilityMatrix {
            get {
                return ResourceManager.GetString("Label_StabilityMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        public static string Label_Steps {
            get {
                return ResourceManager.GetString("Label_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps - Base.
        /// </summary>
        public static string Label_StepsBase {
            get {
                return ResourceManager.GetString("Label_StepsBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps - Refiner.
        /// </summary>
        public static string Label_StepsRefiner {
            get {
                return ResourceManager.GetString("Label_StepsRefiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Label_System {
            get {
                return ResourceManager.GetString("Label_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Label_Theme {
            get {
                return ResourceManager.GetString("Label_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Label_TimePeriod {
            get {
                return ResourceManager.GetString("Label_TimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        public static string Label_UnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("Label_UnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Package.
        /// </summary>
        public static string Label_UnknownPackage {
            get {
                return ResourceManager.GetString("Label_UnknownPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string Label_UpdateAvailable {
            get {
                return ResourceManager.GetString("Label_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAE.
        /// </summary>
        public static string Label_VAE {
            get {
                return ResourceManager.GetString("Label_VAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Type.
        /// </summary>
        public static string Label_VersionType {
            get {
                return ResourceManager.GetString("Label_VersionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to connect....
        /// </summary>
        public static string Label_WaitingToConnectEllipsis {
            get {
                return ResourceManager.GetString("Label_WaitingToConnectEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Label_Width {
            get {
                return ResourceManager.GetString("Label_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete.
        /// </summary>
        public static string Progress_DownloadComplete {
            get {
                return ResourceManager.GetString("Progress_DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading package....
        /// </summary>
        public static string Progress_DownloadingPackage {
            get {
                return ResourceManager.GetString("Progress_DownloadingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete.
        /// </summary>
        public static string Progress_InstallationComplete {
            get {
                return ResourceManager.GetString("Progress_InstallationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing package requirements....
        /// </summary>
        public static string Progress_InstallingPackageRequirements {
            get {
                return ResourceManager.GetString("Progress_InstallingPackageRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing prerequisites....
        /// </summary>
        public static string Progress_InstallingPrerequisites {
            get {
                return ResourceManager.GetString("Progress_InstallingPrerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling package....
        /// </summary>
        public static string Progress_UninstallingPackage {
            get {
                return ResourceManager.GetString("Progress_UninstallingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update complete.
        /// </summary>
        public static string Progress_UpdateComplete {
            get {
                return ResourceManager.GetString("Progress_UpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed.
        /// </summary>
        public static string Progress_UpdateFailed {
            get {
                return ResourceManager.GetString("Progress_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a package to get started!.
        /// </summary>
        public static string TeachingTip_AddPackageToGetStarted {
            get {
                return ResourceManager.GetString("TeachingTip_AddPackageToGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Launch to get started!.
        /// </summary>
        public static string TeachingTip_ClickLaunchToGetStarted {
            get {
                return ResourceManager.GetString("TeachingTip_ClickLaunchToGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your preferred interface and click Install to get started.
        /// </summary>
        public static string Text_OneClickInstaller_SubHeader {
            get {
                return ResourceManager.GetString("Text_OneClickInstaller_SubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the package folder and all its contents, including any generated images and files you may have added..
        /// </summary>
        public static string Text_PackageUninstall_Details {
            get {
                return ResourceManager.GetString("Text_PackageUninstall_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceeding to Launch page.
        /// </summary>
        public static string Text_ProceedingToLaunchPage {
            get {
                return ResourceManager.GetString("Text_ProceedingToLaunchPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunch is required for new language option to take effect.
        /// </summary>
        public static string Text_RelaunchRequiredToApplyLanguage {
            get {
                return ResourceManager.GetString("Text_RelaunchRequiredToApplyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files could not be deleted. Please close any open files in the package directory and try again..
        /// </summary>
        public static string Text_SomeFilesCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("Text_SomeFilesCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Stability Matrix!.
        /// </summary>
        public static string Text_WelcomeToStabilityMatrix {
            get {
                return ResourceManager.GetString("Text_WelcomeToStabilityMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating {0}.
        /// </summary>
        public static string TextTemplate_ErrorUpdatingPackage {
            get {
                return ResourceManager.GetString("TextTemplate_ErrorUpdatingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated to the latest version.
        /// </summary>
        public static string TextTemplate_PackageUpdatedToLatest {
            get {
                return ResourceManager.GetString("TextTemplate_PackageUpdatedToLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0}.
        /// </summary>
        public static string TextTemplate_UpdatingPackage {
            get {
                return ResourceManager.GetString("TextTemplate_UpdatingPackage", resourceCulture);
            }
        }
    }
}
