name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'LykosAI/StabilityMatrix'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
            
      - name: Install dependencies
        run: dotnet restore
        
      - name: Test
        run: dotnet test StabilityMatrix.Tests

      - name: Build
        run: >
          dotnet publish ./StabilityMatrix.Avalonia/StabilityMatrix.Avalonia.csproj 
          -o out -c Release -r linux-x64 
          --self-contained
